name: Automerge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  set-auto-merge:
    name: Set Pull Request do Automerge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setting to Automerge
        uses: heitorpolidoro/automerge-pr@autocreate-pr
        env:
          heitorpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}